### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by tompsota** [tompsota/RideWithMe#10]
- [x] bug - null check operator pocas loading novej jazdy po otvoreni detailu jazdy

   

- [x] #18

   

- [x]  all rides nesmie byt ChangeNotifiere

   

- [x] #11

   

- [x] #12

   

- [x] #14

   

- [x] #15

    

- [x] zapuzdrit Firebase logiku do separatneho repository

   

- [x]  pouzit Stream<List<Ride>> so StreamBuilderom, pricom stream bude mapovany cez aplikovany filter (nezabudnut pouzit .asReuseableStream z Rx Dartu)

    

- [x] rozrefaktorovat dlhe strudle widgetov
